Add Kerbalism Configs for SpaceX & Other Capsules In works.
Standecco/ROKerbalism pull request #80
Opened 2020-11-07 19:30 UTC by vader111

Add Kerbalism Configs for Apollo D2 GE, CST Fixes & SpaceX Capsules.

2020-11-08 12:50 UTC, Standecco requested changes

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		surface = 5.3193     //m^2
Seems definitely wrong, how can a 4.9 m^3 capsule have a 5.3 m^2 surface? Look at the values that the other capsules have, a similar shape and similar volume should result in a similar surface area.

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		surface = 3.728         //m^2
Again, a bit unlikely.

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		%volume = 6.2	//m^3
```suggestion
		%volume = 5.9	//m^3
```
Previous value was sourced, 6.2 is accurate for the proposed block III variant, but not for the actual Apollo CM.

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		%surface = 3.3749	 //m^2
Definitely impossible, the previous surface value was reasonably accurate.
```suggestion
		%surface = 15.71	 //m^2
```

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		%surface = 3.3749	 //m^2
Same as before.

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		%surface = 6.5595	//m^2
Same as before. I also wouldn't remove the previous comments, they're useful enough. Repeating m^3 and m^2 over and over is redundant

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		%volume = 20.8	//m^3 ~ Guess
```suggestion
		%volume = 16.8	//According to ETS wiki
```
The wiki had the mission module IV as having the same habitable volume, but with extra cargo space.

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		%surface = 7.5633	//m^2 ~ Guess
Same as before, this surface value is impossible for that volume.

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		%surface = 4.3267	//m^2
```suggestion
		%surface = 35
```
Again, impossible for that internal volume.

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		%volume = 9	//m^3
The old value was sourced. The difference is almost insignificant, but do you have a reason for the change?

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		%surface = 4.9461	//m^2
```suggestion
		%surface = 35	//m^2
```
Impossible for that internal volume.

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		%max_pressure = 0.35
There are many of these, but almost all of these capsules (everything after Apollo , and everything that is Soviet in general) were used at 1 atm of pressure, so saying that the max pressure these could handle is just 0.35 atm is wrong. There are many more occurrences of this, they should all be brought in line.
```suggestion
```

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/System/Science/HardDriveConfigs.cfg
> +		samples = 3
A bit short on samples? These capsules can return a lot of mass, definitely more than 3 samples worth.

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +@PART[ROC-ApolloCM|ROC-D2MissionModule2|ROC-ApolloCMBlockIII|ROC-OrionCM|ROC-Dragon2CM|ROC-Dragon2CMLunar|ROC-StarshipLunarCM]:NEEDS[ROCapsules,FeatureScience,RP-0]:BEFORE[RP-0-Kerbalism] { %capsuleT
I wouldn't refrain from giving StarshipLunar a Lab module, it's basically a space station on its own

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		%surface = 5.185	// m^2 ~ Calculated from the Internal Model Volume
Not sure what you mean by "internal model volume", but not even a sphere can have that low of a surface area with that high of a volume, same as all the other previous values.

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		%max_pressure = 0.35
Again, these can hold 1 atm of pressure just fine.
```suggestion
```

2020-11-08 12:50 UTC, Standecco commented on GameData/KerbalismConfig/Support/ROCapsules.cfg
> +		%max_pressure = 0.35
Surface area looks sane, but max_pressure should go.
```suggestion
```

2020-11-10 15:32 UTC, vader111 commented
(Ready To Review)

2021-03-25 09:17 UTC, vader111 commented
Split into https://github.com/Standecco/ROKerbalism/pull/92 https://github.com/Standecco/ROKerbalism/pull/93 https://github.com/Standecco/ROKerbalism/pull/94 https://github.com/Standecco/ROKerbalism/pull/95 https://github.com/Standecco/ROKerbalism/pull/96

2021-03-25 09:17 UTC, closed without merging